### ISSUE TITLE
Fortran compilation error (FMS installation) 

### ISSUE THREAD

**Issue by nmathewa** [nmathewa/MOM6dev#38]
Fortran compilation error while making FMS shared code

**Comment by Parag0206** [comment]
If error with SIS2 or MOM6 installation occurs(after FMS is installed) : 
```
error adding symbols: DSO missing from command line
```
this occured for netcdf-c

use the following command
```
export LDFLAGS="-Wl,--copy-dt-needed-entries"
```
and compile netcdf-c again 

then it works(also use triton-gnu.mk)
